
services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: api_transaksi_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - api_network
    command: bash -c "chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"

  nginx:
    image: nginx:1.21-alpine
    container_name: api_transaksi_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - api_network

  db:
    image: mariadb:10.8
    container_name: api_transaksi_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local